// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8UmhqX0iT4V-2XpQ_cvDP-bWDq7wK47c',
    appId: '1:1035993704196:web:a9f128262bf422f144d251',
    messagingSenderId: '1035993704196',
    projectId: 'social-app-62e3e',
    authDomain: 'social-app-62e3e.firebaseapp.com',
    storageBucket: 'social-app-62e3e.appspot.com',
    measurementId: 'G-XMGB638P2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbUKSW_BXxGqUjli8w1YQZ_py3Ru9vC8',
    appId: '1:1035993704196:android:c37e16910e7b7bcd44d251',
    messagingSenderId: '1035993704196',
    projectId: 'social-app-62e3e',
    storageBucket: 'social-app-62e3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcGmg-ERlZeEXP7bxQ059qIp5dLLGENFo',
    appId: '1:1035993704196:ios:505e4f51958deca844d251',
    messagingSenderId: '1035993704196',
    projectId: 'social-app-62e3e',
    storageBucket: 'social-app-62e3e.appspot.com',
    iosBundleId: 'com.example.socialapp',
  );
}
